---
title: Näringslivet i Dalarna
author: ""
date: ""
output: 
  html_document:
    self_contained: true
    includes:
      in_header: 
      - favicon.html
      - hero_image.html
    toc: yes
    toc_float: yes
    toc_depth: 6
    css: "styles_hero.css"
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.height=5, fig.width=8, fig.align='center')

# Nödvändiga paket
if (!require('pacman')) install.packages('pacman')
p_load(tidyverse,
       here)

# Funktioner som behövs (hämtas från Git-Hub)
source('https://raw.githubusercontent.com/Region-Dalarna/funktioner/main/func_SkapaDiagram.R')
source('https://raw.githubusercontent.com/Region-Dalarna/funktioner/main/func_API.R')

# För att information från Tidyverse inte skall visas
options(dplyr.summarise.inform = FALSE)

```

```{js}
const debounce = (fn) => {
  let frame;
  return (...params) => {
    if (frame) cancelAnimationFrame(frame);
    frame = requestAnimationFrame(() => fn(...params));
  };
};

const storeScroll = () => {
  const threshold = 150; // px
  const scrolled = window.scrollY > threshold;

  document.documentElement.dataset.scroll = scrolled ? 'scrolled' : 'top';
};

document.addEventListener('scroll', debounce(storeScroll), { passive: true });
storeScroll();

```
<p style = "font-size:12px">
<i>Rapporten är skapad av Samhällsanalys, Region Dalarna<br>
Senast uppdaterad: `r Sys.Date()`</i>
</p>

# Sammanfattning {-}

Här ska vi ha en sammanfattning av rapporten. Det ska vara en punktlista med de viktigaste budskapen och inte ett referat av varje avsnitt.
<br>

<ul>

<li>Första punkten. </li>

<li>Andra punkten. </li>
    
<li>Tredje punkten. </li>

<li>Fjärde punkten. </li>

</ul>

# Introduktion {-}

Röd tråd! Viktigt att det som är med behövs för att ge en bra berättelse. 

Vad vill vi uppnå? Hur gör vi det smidigast? Övergripande slutsatser och analys i rapport med ett fåtal diagram som stödjer slutsatser, men möjlighet att länka vidare till en mer omfattande rapport (Shiny?) där användaren kan ta del av mer detaljer kring näringslivet i länet?

Bidra med kunskap om länets näringsliv och vägleda strategiska och finansiella insatser.
Öka kunskapen om Dalarnas näringslivsstruktur och utveckling.

I denna rapport beskrivs näringslivet i Dalarna. Näringslivet definieras som de delar i ekonomin som tillverkas och säljs på en marknad, både varor och tjänster, och är i huvudsak privat ägd. I näringslivet ingår dock även offentlig verksamhet som drivs i bolagsform. Renodlad offentlig verksamhet som finansieras genom skatter och avgifter ingår inte i näringslivsdefinitionen. Däremot är den offentliga verksamheten ofta viktig för näringslivet, vilket gör att den behöver beskrivas och ställas i relation till näringslivet för att förstå hela ekonomin. 

Rapporten inleds med en övergripande bild av näringslivet, följt av en genomgång av länets utveckling när det gäller länets bruttoregionprodukt och företagens lönsamhet. Därefter ges information och import, export samt sysselsättning. Rapporten avslutas med avsnitt som behandlar lokalt, socialt samt hållbart företagande i länet.

Vilka är betydande för Dalarnas ekonomi - nu och historiskt?
Hur konkurrenskraftiga är företag och branscher i ett nationellt perspektiv?
Hur ser branschstrukturen ut - mix av stora och små, lönsamma företag?
Koppling mot internationella marknader, kunskapsintensitet och förnyelseförmåga?

Syftet med rapporten är att beskriva näringslivet i Dalarna och dess förutsättningar. Den huvudsakliga källan är SCB. Ambitionen är inte att ge en dagsaktuell bild av läget i näringslivet, utan en bredare beskrivning. Det innebär att de data som används är i stora delar för kalenderåret 2024. 

Urvalet av verksamheter som ingår hämtas från SCB:s Företagsdatabas och de inkluderade företagen har avgränsats till att ha

<ul>

<li>Minst 500 000 kronor i omsättning </li>
    
<li>Status som aktiva och F-skatt </li>

</ul>

Vilket datum gäller för uttag ur FDB?

Verksamheter inom offentlig sektor är exkluderade, även om de har betydelse för företag i privat sektor i form av kunder. Således kan förändringar inom offentligt sektor få effekt på utvecklingen för företag i privat sektor.

Var tydlig med när den offentliga sektorn är inkluderad eller inte. När behövs den för att sätta proportioner mot det privata?

Arbetsställen behöver också hanteras i någon form eftersom stora företag som är en del av Dalarnas näringsliv har sina säten i andra län. Då behöver arbetsställen som finns i länet och bidrar komma med i analysen.

Ge en kort sammanfattning inledningsvis i respektive avsnitt?

# Dalarnas näringsliv och företagande
Några övergripande basfakta om Dalarnas näringsliv och företag

Senaste mättillfället samt för 10 och 20 år sedan?

Antal företag i urvalet
Antal anställda
Omsättning

https://www.foretagsklimat.se/dalarnas-lan

Grov branschindelning med omsättning och sysselsättning per bransch
5 största företagen per bransch och deras omsättning och sysselsättning

Skapa kommunflikar med motsvarande indelning som är klickbara
3 största företagen per bransch och deras omsättning och sysselsättning


Total import och export?

Förändring i näringslivets sammansättning de senaste x åren?

LA- och FA-regioner?

## Näringslivets omfattning, utveckling och geografisk fördelning
Ett antal diagram som ger en bild av näringslivets sammansättning i Dalarna.

Största arbetsgivare i länet och per kommun.

## Branscher - omsättning och sysselsatta
Bubbeldiagrammet?

Blekinge använder samma indelning som Region Skåne, vilket är 40 olika branscher utifrån SNI-indelning.
Små branscher exkluderas (<50 anställda).
Exkluderar även vissa företag som har stora kapitalrörelser mellan åren, fastighet, finans, försäkring
Justering av löpande till fasta priser?

## Kommunala variationer
Här kommenterar vi hur det ser ut i våra kommuner, vilka skillnader som finns m m.

# Regionalräkenskaper (BRP)
Titta tillbaka på utvecklingen för BRP i länet, jämfört med riket och i ett EU-perspektiv.

Hur förhåller sig dessa siffror till det privata respektive det offentliga?

Mer aktuella delar får flyttas in i "Det samhällsekonomiska läget" och vi hänvisar dit för mer aktuell information.

Finns det behov av att visa på vilket konjunkturläge som råder innan vi visar hur det går i näringslivet? Något från SCB:s konjunkturklocka som kan nyttjas?

Sammanställning av utvecklingen av tillväxt, förädlingsvärden, produktivitet, lönesummor per bransch och skattekraft.

Förädlingsvärdet mäts vanligen som värdet av företagets produktion minus värdet 
av insatsvarorna i produktionen och utgör ett företags bidrag till landets BNP. Summan av alla 
förädlingsvärden vid samtliga arbetsställen utgör landets BNP. På motsvarande sätt är summan av de 
förädlingsvärden som genereras vid samtliga arbetsställen i en region bruttoregional produkten (BRP). Per 
definition summerar regionernas BRP upp till landets BNP.

## Tillväxt
Vad kan vi säga om utvecklingen när det gäller ekonomisk tillväxt?
Den ekonomiska tillväxten mäts som förändringen i Bruttonationalprodukten (BNP) mellan två tidsperioder. Det ekonomiska välståndet definieras som nivån på BNP vid en viss tidpunkt.

## Produktivitet
Hur har arbetsproduktiviteten utvecklats i länet? För att mäta produktivitet används arbetsproduktiviteten som definieras som förädlingsvärdet per arbetsinsats (vanligen antal arbetade timmar). Enklare uttryckt visar arbetsproduktiviteten hur mycket värde som skapas per arbetad timma. På regional nivå finns inte arbetade timmar tillgängligt, vilket innebär att produktiviteten mäts genom förädlingsvärdet dividerat med antal sysselsatta. 

## Förädlingsvärden
Förädlingsvärden förklaras och redovisas per bransch om möjligt.
Ett företags förädlingsvärde är det värde som skapas i verksamheten, eller enklare uttryckt det värde som företaget självt skapar. Förädlingsvärdet mäts vanligen som värdet av företagets produktion minus värdet av insatsvarorna i produktionen och utgör ett företags bidrag till landets BNP. Summan av alla förädlingsvärden vid samtliga arbetsställen utgör landets BNP. På motsvarande sätt är summan av de förädlingsvärden som genereras vid samtliga arbetsställen i en region bruttoregional produkten (BRP). Per definition summerar regionernas BRP upp till landets BNP.

# Företagens lönsamhet
Här tittar vi på lönsamhetsmått, hur nyföretagandet utvecklas och hur företagens överlevnadsgrad ser ut på kort och lång sikt.

# Shift-share eller specialisering?
Är det här något vi borde inkludera?

## Lönsamhetsmått
Earnings Before Interest and Taxes (EBIT), Return on Assets (ROA) och Return on Equtiy (ROE).

## Nyföretagande och Överlevnadsgrad
Hur är situationen när det gäller tillkomsten av nya företag och hur ser överlevnadsgraden ut över tid? Startas det många bolag som sedan inte finns kvar efter några år?

Karta över nyföretagande per 1000 invånare per kommun

# Internationella relationer
Här tittar vi på näringslivet i Dalarnas export- och importvolymer. Något att hämta från det pågående arbetet med export- och insammanställning?

## Export

## Import

## Utländskt ägande
Tillväxtanalys har information om utlandsägande m m

# Arbetskraften  
Vad är viktigt för näringslivsperspektivet?
Vilka är det som är sysselsatta? 
På branschnivå?
Vilken utbildning har de?
Hur väl matchade är de i sina yrken?
Pendlar de till arbetet?

Vilken potential finns det för näringslivet att utvecklas utifrån arbetskraftens sammansättning?

# Det lokala företagandet
Vad kan vi säga om hur företag ägs och sysselsätter sin verksamhet lokalt? Hur beroende är Dalarnas företag av marknader utanför länet och utanför riket?

Utlandsägda företag/arbetsställen (hanteras under internationella relationer, men kan även vara en dimension i en lokal genomgång)

# Det sociala företagandet
Finns det något vi kan göra för att beskriva den sociala dimensionen i länets företagande?

# Det hållbara företagandet
Energiförbrukning
Minskade CO2-utsläpp
Grön omställning m m 

# Avslutande diskussion
Vad kan vi säga om denna genomgång?

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 200px;"></div>

